api/urls.py
from django.urls import include, path
from api import views


app_name = 'api'

urlpatterns = [
    path('generate-post/', views.PostView.as_view(), name="post"),
]

core/urls.py
from django.urls import include, path
from core import views


app_name = 'core'

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('account/login/', views.CoreLoginView.as_view(), name='login'),
    path('account/logout/', views.CoreLogoutView.as_view(), name='logout'),
    path('add-post/', views.CretePostView.as_view(), name='create')
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

core/models.py
from django.db import models


class SocialPost(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    date_scheduling = models.DateTimeField()
    social = models.CharField(max_length=225)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

core/forms.py
from django import forms
from core.models import SocialPost


class SocialPostForm(forms.ModelForm):
    social = forms.CharField(required=False)

    class Meta:
        model = SocialPost
        fields = "__all__"
    
    def clean_social(self):
        value = ', '.join(self.data.getlist('social[]'))
        return value
    

api/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from api.serializers import PostSerializer


class PostView(APIView):
    
    def post(self, request, format=None):
        serializer = PostSerializer(data=request.data)
        if serializer.is_valid():
            obj = serializer.save()
            return Response(obj, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

core/views.py
from django.shortcuts import render
from django.views import generic
from django.views.generic.edit import CreateView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin

from core.forms import SocialPostForm
from core.models import SocialPost


class CoreLoginView(LoginView):
    template_name = 'core/auto/login.html'
    redirect_authenticated_user = True
    next_page = 'core:index'


class CoreLogoutView(LogoutView):
    next_page = 'core:index'


class IndexView(LoginRequiredMixin, generic.TemplateView):
    template_name = "core/index.html"
    login_url = "account/login/"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['module'] = "LISTAGEM"
        context['social_posts'] = SocialPost.objects.all()
        return context


class CretePostView(LoginRequiredMixin, CreateView):
    template_name = "core/post-create.html"
    login_url = "account/login/"
    form_class = SocialPostForm
    success_url = '/'
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['module'] = "ADICIONAR"
        return context
    
    def form_invalid(self, form):
        print(form.errors)
        return self.render_to_response(self.get_context_data(form=form))

frontend/templates/core/auto/login.html
{% load static %}

<!doctype html>
<html lang="en" data-bs-theme="auto">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#712cf9">

    <title>SGP-Login</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

    <style>
        html,
        body {
            height: 100%;
        }

        .form-signin {
            max-width: 340px;
            padding: 1rem;
        }

        .form-signin .form-floating:focus-within {
            z-index: 2;
        }

        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
        .btn-primary {
            background-color: #739822 !important;
            border: none;
        }
    </style>
</head>

<body class="d-flex align-items-center py-4 bg-body-tertiary">
    <main class="form-signin w-100 m-auto">

        {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert" style="font-size: 0.8em;" >
            {{ form.non_field_errors}}
        </div>
        {% endif %}

        <form action="{% url 'core:login' %}?next=/" method="POST"
            class="d-flex flex-column align-items-center"> {% csrf_token %}
            <img class="mb-4" src="{% static 'img/logo-proffer2.png' %}" alt="Logo da proffer" height="65">
            
            <h1 class="h3 mb-3 fw-normal">Admin</h1>

            <div class="input-group mb-3">
                <span class="input-group-text">
                    <i class="bi bi-person-circle" style="font-size: 6mm;"></i>
                </span>
                <div class="form-floating">
                    <input type="text" class="form-control" id="username" name="username" placeholder="Username" required>
                    <label for="username">Username</label>
                </div>
            </div>
            <div class="input-group mb-3">
                <span class="input-group-text">
                    <i class="bi bi-file-lock2" style="font-size: 6mm;"></i>
                </span>
                <div class="form-floating">
                    <input type="text" class="form-control" id="password" name="password" placeholder="password" required>
                    <label for="username">Password</label>
                </div>
            </div>

            <button class="btn btn-primary w-100 py-2" type="submit">Acessar</button>
            <p class="mt-5 mb-3 text-body-secondary">&copy; {% now "Y" %}</p>
            <input type="hidden" name="next" value="{{ next }}">
        </form>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

frontend/templates/core/base/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Proffer - SGP{% endblock %}</title>

    {% block styles %}
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <!-- Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    
    <!-- Toastify -->
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">

    <link href="{% static 'css/admin.css' %}" rel="stylesheet">
    {% endblock %}
</head>

<body>
    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap justify-content-start p-0 shadow">
        <div class="navbar-brand col-5 col-md-3 col-lg-2 me-0 ps-3 pt-2">
            <button class="navbar-toggler d-md-none collapsed" type="button" data-bs-toggle="collapse"
                data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <span class="ms-2 ms-md-5 fw-bold">ADMIN</span>
        </div>
        <span class="d-none d-sm-inline fw-bold ms-auto me-3 ms-md-3">
            PROFFER
            <!--img src="{% static 'img/logo-proffer.png' %}" height="40px"-->
        </span>
        <span class="ms-auto me-3">
            Bem-vindo, {{ user.username }}!
        </span>
    </header>

    <div class="container-fluid wrapper">
        <div class="row">

            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-dark sidebar collapse">
                <div class="position-sticky pt-3">
                    {% include "core/shared/menu.html" %}
                </div>
            </nav>

            <main class="col-md-9 ms-sm-auto col-lg-10 px-1 px-md-4 py-3">
                <div class="container bg-white px-0 py-4 px-md-4">
                    {% include "core/shared/bar.html" with modulo=modulo %}
                    {% block content %} {% endblock %}
                </div>
            </main>
        </div>
    </div>

    <div id="spinner" class="modal" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content border-0 bg-transparent">
                <div class="modal-body">
                    <div class="d-flex justify-content-center">
                        <div class="spinner-grow text-info" style="width:5rem; height:5rem;" role="status">
                            <span class="visually-hidden">Loading...</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>

    {% block javascript %} {% endblock %}
</body>

</html>

frontend/templates/core/index.html
{% extends 'core/base/base.html' %}
{% load static %}

{% block title %}SGP - index{% endblock %}

{% block content %}
<div class="p-1 p-sm-5 border">
    <div class="mt-3 d-flex">
        <a class="btn btn-primary ms-auto" href="{% url 'core:create' %}" role="button">
            <i class="bi bi-plus-circle"></i>
            Adicionar
        </a>
    </div>
    <div class="mt-1 table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col" width="40%">Título</th>
                    <th scope="col">Agendado Para</th>
                    <th scope="col">Plataformas</th>
                    <th scope="col">Criado Em</th>
                </tr>
            </thead>
            <tbody id="postList">
                {% for obj in social_posts %}
                <tr>
                    <td>{{ forloop.counter }} </td>
                    <td>{{obj.title}}</td>
                    <td>{{obj.date_scheduling}}</td>
                    <td>{{obj.social}}</td>
                    <td>{{ obj.created_at|date:"d/m/y" }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="5">Sem resultados.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block javascript %}
{% endblock %}

frontend/templates/core/post-create.html
{% extends 'core/base/base.html' %}
{% load static %}

{% block title %}SGP - Add{% endblock %}

{% block styles %}
{{ block.super }}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<link href="{% static 'css/post-create.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="p-1 p-sm-4 border">
    <div class="">
        <form id="regForm" action="{% url 'core:create' %}" method="post">
            {% csrf_token %}
            <ul class="form-stepper form-stepper-horizontal text-center">
                <li class="form-stepper-active text-center form-stepper-list" step="1">
                    <a class="mx-1">
                        <span class="form-stepper-circle">
                            <span>1</span>
                        </span>
                    </a>
                </li>
                <li class="form-stepper-unfinished text-center form-stepper-list" step="2">
                    <a class="mx-1">
                        <span class="form-stepper-circle text-muted">
                            <span>2</span>
                        </span>
                    </a>
                </li>
                <li class="form-stepper-unfinished text-center form-stepper-list" step="3">
                    <a class="mx-1">
                        <span class="form-stepper-circle text-muted">
                            <span>3</span>
                        </span>
                    </a>
                </li>
            </ul>

            <div class="border rounded rounded p-4 mt-1">
                <div class="tab">
                    <div class="mb-3">
                        <label for="title" class="form-label">Título</label>
                        <input type="text" class="form-control valid" id="title">
                    </div>
                    <div class="mb-3">
                        <label for="description" class="form-label">Descrição</label>
                        <textarea class="form-control valid" id="description" rows="3"></textarea>
                    </div>
                </div>

                <div class="tab">
                    <div id="spinner-div" class="d-flex align-items-center pb-2">
                        <strong id="labelSpinner">Loading...</strong>
                        <div id="spinner" class="spinner-border text-success ms-auto" role="status" aria-hidden="true"></div>
                    </div>
                    <div class="mb-3">
                        <label for="title" class="form-label">Título</label>
                        <input type="text" class="form-control" id="titleSug" readonly>
                    </div>
                    <div class="mb-3">
                        <label for="suggestion" class="form-label">Sugestão</label>
                        <textarea class="form-control" id="suggestion" rows="5"></textarea>
                    </div>
                    <div>
                        <span>Tags:</span>
                        <div id="tagsDiv"></div>
                    </div>
                </div>
                
                <div class="tab">
                    <div class="row">
                        <div class="col">
                            <div class="mb-3">
                                <label for="title" class="form-label">Título</label>
                                <input id="titlePost" type="text" class="form-control" name="title">
                            </div>
                            <div class="mb-3">
                                <label for="content" class="form-label">Texto</label>
                                <textarea class="form-control" id="contentPost" rows="10" name="content"></textarea>
                            </div>
                        </div>
                        <div class="col">
                            <div>
                                <label for="date_scheduling" class="form-label">Agendar para:</label>
                                <div class="input-group mb-3">
                                    <span class="input-group-text">
                                        <i class="bi bi-calendar3"></i>
                                    </span>
                                    <input id="dateScheduling" type="text" class="form-control" name="date_scheduling">
                                </div>
                            </div>
                            <div>
                                <input type="checkbox" name="social[]" value="facebook" class="btn-check" id="facebook" autocomplete="off">
                                <label class="btn btn-outline-primary" for="facebook">
                                    <i class="bi bi-instagram"></i> Facebook
                                </label>
                                
                                <input type="checkbox"  name="social[]" value="instagram" class="btn-check" id="instagram" autocomplete="off">
                                <label class="btn btn-outline-primary" for="instagram">
                                    <i class="bi bi-facebook"></i> Instagram
                                </label> 

                                <input type="checkbox"  name="social[]" value="linkedin" class="btn-check" id="linkedin" autocomplete="off">
                                <label class="btn btn-outline-primary" for="linkedin">
                                    <i class="bi bi-linkedin"></i> Linkedin
                                </label>
                            </div>
                        </div>
                    </div>
                </div>

                <div style="overflow:auto;">
                    <div style="float:right;">
                        <button type="button" class="btn btn-primary" id="prevBtn">Voltar</button>
                        <button type="button" class="btn btn-primary" id="nextBtn">Proxímo</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block javascript %}
{{ block.super }}
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="{% static 'js/post-create.js' %}"></script>
{% endblock %}

frontend/templates/core/shared/bar.html
<div class="position-relative">
    <div class="py-1 px-3 position-relative module-bar">
        <h4 class="pt-1 fs-5">
            {{module}}
        </h4>
    </div>
<div>

frontend/templates/core/shared/menu.html
<ul class="nav flex-column">
    <li class="nav-item">
        <a class="nav-link {% if module == 'LISTAGEM' %} active {% endif %}"
           href="{% url 'core:index' %}">
            <i class="bi bi-house-door-fill me-1"></i>
            Home
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if module == 'ADICIONAR' %} active {% endif %}" 
            href="{% url 'core:create' %}">
            <i class="bi bi-file-earmark-post-fill me-1"></i>
            Postagem
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link danger" href="{% url 'core:logout' %}">
            <i class="bi bi-door-closed-fill me-1"></i>
            Sair
        </a>
    </li>
</ul>